config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/invite', to: 'invitations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'signup', to: 'users#new'
  resources :users
  resources :events
  resources :invitations, only: [:create]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_attendee, foreign_key: :event_id
  has_many :attendees, through: :event_attendee
  has_many :invitations, foreign_key: :event_id
  has_many :invitees, through: :invitations
  belongs_to :creator, class_name: 'User', foreign_key: :user_id
  scope :upcoming, -> { where('date > ?', DateTime.now) }
  scope :past, -> { where('date < ?', DateTime.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitee, class_name: 'User', foreign_key: :invited_user_id
  belongs_to :invited_event, class_name: 'Event', foreign_key: :event_id
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :events, dependent: :delete_all
  has_many :event_attendees, foreign_key: 'user_id'
  has_many :attended_events, through: :event_attendees
  has_many :invitations, foreign_key: 'invitee'
  has_many :invited_events, through: :invitations
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def upcoming_events
    invited_events.upcoming
  end

  def past_events
    invited_events.past
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?
  helper_method :current_user
  # Confirms a logged-in user.
  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, except: %i[index show]
  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(events_params)
    if @event.save
      flash[:success] = 'Event created successfully'
      redirect_to @event
    else
      render :new
    end
  end

  def index
    @upcoming_events = Event.upcoming.order(date: :desc)
    @past_events = Event.past.order(date: :desc)
  end

  def show
    @event = Event.find(params[:id])
    @attendees = Invitation.where(event_id: @event.id)
  end

  private

  def events_params
    params.require(:event).permit(:title, :description, :date, :location)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    @invitation.invited_user_id = User.find_by(email: @invitation.email).id
    if @invitation.save
      flash[:notice] = 'Invitation sent'
      redirect_to event_path(params[:invitation][:event_id])
    else
      flash[:warn] = 'Error occured: try again'
      redirect_to invite_path(eventid: params[:invitation][:event_id])
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:email, :event_creator, :event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'welcome to our site'
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Your account is created successfully'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Your account is updated successfully'
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendee_helper.rb
module EventAttendeeHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  # def same_user?(user)
  #   @current_user.id == user.id
  # end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_events.html.erb
   <% obj.each do |event| %>
   
       <h4 class="badge badge-light">Title:</h4>  <%= event.title %><br>
       <h4 class="badge badge-light">Description:</h4>  <%= event.description %><br>
       <h4 class="badge badge-light">Location:</h4>  <%= event.location %><br>
       <h4 class="badge badge-light">Date:</h4>  <%= event.date %><br>
       <h4 class="badge badge-light">Created by:</h4>  <%= event.creator.name %><br>
       
       <%= link_to 'Show',event_path(event), class: "btn btn-primary" %>
         <hr>
   <% end %>

app/views/events/index.html.erb
<div class="container-fluid">
    <h1>All Events</h1>
    <div class="row">
        <div class="col-xs-6 upcoming-events">
            <h2 class="upcoming">Upcoming Events</h2>
            <%= render 'events', obj: @upcoming_events %> 
        </div>
        <div class="col-xs-6 past-events">
            <h2>Past Events</h2>
            <%= render 'events', obj: @past_events %>
        </div>
    </div>
</div>

app/views/events/new.html.erb
 
 <div class="event-form">
 
 <%= form_for (@event) do |f| %>
  <%= render 'shared/error_messages', object:@event %>
  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
 </div>
 <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description %>
</div>
   <div class="form-group">
      <%= f.label :date %>
      <%= f.datetime_select :date %>
   </div>   
      <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location %>
    </div>
      <%= f.submit "Create Event", class: "btn btn-primary" %>
<% end %>
</div>

app/views/events/show.html.erb
            <h1><%= @event.title %></h1>
        <div class ="event-show">
            <p> Created by <%= @event.creator.name %></p>
              <h4>Description:</h4>  <%= @event.description %><br>
                <h4>Date:</h4><%= @event.date %><br>
                <h4>Location</h4><%= @event.location %><br>
         
                <% if log_in(@event.creator) && @event.date > DateTime.now %>
                    <%= link_to "Invite", invite_path(eventid: @event.id) , class: "btn btn-primary w-25 float-right" %>
                <%end%>
         </div>  
        <h2>Attendees</h2>
        <%if @attendees.empty? %>
            <h3 class="text-center">There is no attendees</h3>     
        <%else%>
            <% @attendees.each do |attendee|%>
                <hr>
                <h3><%=attendee.email%></h3>
            <%end%>
        <%end%>
 

app/views/invitations/new.html.erb
<div class= "invitation">
<%= form_for @invitation do |f| %>
<%= render 'shared/error_messages', object:@invitation %>
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, required: true, placeholder: 'example@mail.com' ,class: 'form-control m-2' %>
      <%= f.hidden_field :event_id, value: params[:eventid] %>
      <%= f.hidden_field :event_creator, value: current_user.id %>
      <%= f.submit "Invite", class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
	  <%= link_to "PRIVATE EVENTS", root_path, id: "logo" %>
		<nav>
		  <ul class="nav navbar-nav navbar-right">
			  <li><%= link_to "Home",    root_path %></li>
				
				<% if logged_in? %>
				    <li><%= link_to "All Event",events_path %></li>
					<li><%= link_to "Create new Event",new_event_path %></li>
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
						  Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
						  <li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "all users", users_path %></li>
							<li class="divider"></li>
							<li>
							  <%= link_to "Log out", logout_path, method: :delete %>
							</li>
						</ul>
					</li>
				<% else %>
				<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> |PrivateEvents </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
  </head>
  </html>
  
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  </div>
    <%= yield %>
  </body>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_list_events.html.erb
<%if events.blank? %>
    <h3 class="text-center p-5">No <%= type%> events</h3>
<% else %>
    <% events.each do |e| %>
        <div class="card m-4">
            <div class="card-body">
                <h5 class="card-title"><%= e.title%></h5>
                <p class="card-text"><%= e.description%></p>
                <%= link_to "View", event_path(e.id), class: "btn btn-primary float-right"%>
            </div>
            <div class="card-footer text-muted text-right">
                <%= type == 'past' ? time_ago_in_words(e.date) : e.date %>
                <%if type == 'past'%>
                <span> ago</span>
                <%end%>    
            </div>
        </div>
    <% end %>

<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>PrivateEvents</h1>
<h2>
    Welcome to PrivateEvents <br><br>
<% if !logged_in? %>
    <%= link_to " Register now ! ", signup_path, class: "btn btn-primary btn-lg more", role: "button" %>
<% end %>
</h2>
<p>
  <img class ="img" src="/assets/event.png" alt="events" />
</p>

app/views/users/_form.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object:@user %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
     
      <%= f.submit(@user.new_record? ? "Create User":"Update account", class: "btn btn-primary")%>
    <% end %>
  </div>
</div>

app/views/users/_user_events.html.erb
<%if events.blank? %>
    <h3 class="text-center p-5">No <%= type%> events</h3>
<% else %>
    <% events.each do |e| %>
                <h5 class="card-title"><%= e.title%></h5>
                <p class="card-text"><%= e.description%></p>
                <%= link_to "View", event_path(e.id), class: "btn btn-primary float-right"%>
                <%= type == 'past' ? time_ago_in_words(e.date) : e.date %>
                <%if type == 'past'%>
                <span> ago</span>
                <%end%>    
    <% end %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>
<% @user.each do |u| %>
   
      <span class="badge badge-light">Name:</span> <%= u.name %><br>
       <span class="badge badge-light">Email:</span><%= u.email %><br>
   
   <span class="badge badge-light">Created:</span><%= pluralize(u.events.count, "event") if u.events %>
   <%= link_to 'Show',user_path(u) ,class: "btn btn-primary" %>
   <hr>
<% end %>

app/views/users/new.html.erb
<h1> Create account </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1>My profile</h1>
<br>
<h1><%= @user.name %></h1>
<h3><%= @user.email %></h3>

<h2>Events</h2>

   
                <%= render 'user_events', {events: @user.upcoming_events, type: 'upcoming'} %>
     
                <%= render 'user_events', {events: @user.past_events, type: 'past'} %>         
    
                <%= render 'user_events', {events: @user.events, type: 'created'} %>         
  